# @example Use base config for all Piktur gems
#   inherit_gem:
#     piktur: .rubocop.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'lib/**/generators/**/*'
    - 'test/dummy/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4.1
  TargetRailsVersion: 5.0

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: table

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

# Checks formatting of special comments
Style/CommentAnnotation:
  Keywords:
    - '@example'
    - '@note'
    - '@return'
    - '@see'
    - '@todo'
    - '@yieldparam'

Style/Copyright:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/Encoding:
  EnforcedStyle: when_needed

Style/FileName:
  ExpectMatchingDefinition: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: when_needed

Style/IfUnlessModifier:
  MaxLineLength: 100

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Style/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/Next:
  EnforcedStyle: skip_modifier_ifs

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/**/spec/**/*'

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: true
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/TrivialAccessors:
  ExactNameMatch: true
  AllowPredicates: false

Style/WhileUntilModifier:
  MaxLineLength: 100

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 1

Style/SymbolArray:
  Enabled: false
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: true
  Exclude:
    - 'lib/**/test_helpers.rb'
    - 'spec/**/*'
    - 'test/**/*'

Style/PerlBackrefs:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ColonMethodCall:
  Enabled: false

Style/LambdaCall:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - lib/spec/**/*.rb
    - spec/**/*.rb
  CountComments: false
  Max: 25
  ExcludedMethods:
    - context
    - describe
    - it
    - specify
    - let
    - let!
    - subject
    - before
    - around
    - shared_context
    - shared_examples
    - configure
    - included
    - new

Metrics/BlockNesting:
  Max: 3
  Exclude:
    - lib/spec/**/*.rb
    - spec/**/*.rb

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/LineLength:
  Max: 100
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoreCopDirectives: true
  IgnoredPatterns:
    - !ruby/regexp /\A\s*# @todo/
    - !ruby/regexp /\A\s*# @note/
    - !ruby/regexp /\A\s*# @see/
    - !ruby/regexp /\A\s*# @example/

Metrics/MethodLength:
  CountComments: false
  Max: 10

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UnusedBlockArgument:
  IgnoreEmptyBlocks: true
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
  IgnoreEmptyMethods: true

Lint/InheritException:
  EnforcedStyle: standard_error

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Rails:
  Enabled: true

Rails/Date:
  EnforcedStyle: flexible

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_class # FactoryGirl helper

Rails/Exit:
  Exclude:
    - bin/*
    - Rakefile
    - lib/**/cli.rb
    - lib/**/*.rake

Rails/SaveBang:
  Enabled: true
