# frozen_string_literal: true

gh = 'https://github.com'
bb = 'https://bitbucket.org'

source 'https://rubygems.org'
source ENV['GEM_SOURCE']

ruby '2.3.0'

gemspec name: 'piktur_<%= app_name %>'

# @!group Piktur
gem 'piktur',                   git:    "#{bb}/piktur/piktur.git",
                                branch: 'master'
# gem 'piktur_core',              git:    "#{bb}/piktur/piktur_core.git",
#                                 branch: 'master'
# @!endgroup
<% gemfile_entries.each do |gem| -%>
<% if gem.comment -%>

# <%= gem.comment %>
<% end -%>
<%= gem.commented_out ? '# ' : '' %>gem '<%= gem.name %>'<%= %(, '#{gem.version}') if gem.version -%>
<% if gem.options.any? -%>
, <%= gem.options.map { |k,v|
  "#{k}: #{v.inspect}" }.join(', ') %>
<% end -%>
<% end -%>

